<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllContacts()
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT u.name, u.surname, p.phoneNumber FROM AppBundle:User u JOIN u.phone AS p WHERE u.id>0");
        $contacts = $query->getResult();
        return $contacts;
    }
}
